name: CI-CD-Workshop

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          cd root/backend
          go get .
      - name: Build
        run: |
          cd root/backend
          go build -v ./...
      - name: Test with the Go CLI
        run: |
          cd root/backend
          go test
