name: Palpline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GO_VERSION }}
                
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Build frontend
              working-directory: ./frontend
              run: npm ci && npx ng build && cp -r dist/frontend/browser ../backend/cmd/strichliste/frontendDist

            - name: Run tests
              working-directory: ./backend
              run: go test ./...