name: Pallpline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GO_VERSION }}
                
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Build frontend
              working-directory: ./frontend
              run: npm ci && npx ng build && cp -r dist/frontend/browser ../backend/cmd/strichliste/frontendDist

            - name: Run tests
              working-directory: ./backend
              run: go test ./...

            - name: Create test report
              working-directory: ./backend
              run: go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html

            - name: Setup SSH
              run: |
                # setup / start ssh auth socket which manages our ssh keys when connecting to other servers via ssh
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                # load the private key
                mkdir ~/.ssh
                chmod 700 ~/.ssh
                echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                # setup known hosts
                echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
              env: 
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock

            - name: Push test coverage report
              run: scp backend/coverage.html group10@hoenle.xyz:/var/www/group10/coverage.html
