name: "Pallpline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Attention: you want to put version numbers like this in quotes! 
  # Else they will maybe interpreted as a number, which will e.g. remove traling zeros.
  GO_VERSION: "1.23.4"
  NODE_VERSION: "22.11.0"
  CONTAINER_IMAGE_NAME: "ghcr.io/rubenhoenle/ci-cd-lecture-project-template"
  CONTAINER_IMAGE_TAG: "latest"

jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [arm64, amd64]
    runs-on: ubuntu-latest
    steps:
    - name: Set GOOS and GOARCH
      run: |
        export GOOS=${{ matrix.os }}
        export GOARCH=${{ matrix.arch }}
      
  code-format:
    name: "Check code format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Check code format (backend)
        run: files=$(gofmt -l ./backend) && [ -z "$files" ]

      - name: Install npm dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Check code format (frontend)
        working-directory: ./frontend
        run: npx prettier --check .

  backend:
    name: "Backend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
      
      - name: Install npm dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npx ng build

      - name: Copy frontend build result
        run: cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist
      
      - name: Run backend unit tests
        working-directory: ./backend
        run: go test ./...

      - name: Create test coverage report
        working-directory: ./backend
        run: go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html

      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: ./backend/coverage.html
          retention-days: 14
          
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: build_image
        with:
          push: false  # Don't push yet, we will push after tests
          tags: ghcr.io/philipp-engelhardt/pallpline:latest

      - name: Start container
        run: |
          docker run -d --rm -p 8080:8080 --name test_container ghcr.io/philipp-engelhardt/pallpline:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Wait for container to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Container is ready."; exit 0;
            fi
            echo "Waiting for container..."; sleep 2;
          done
          echo "Container did not become ready in time."; exit 1

      - name: Run smoke tests
        run: |
          cd backend
          go run ./cmd/smoketest/

      - name: Stop and remove container
        if: always()
        run: |
          docker stop test_container

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/philipp-engelhardt/pallpline:latest

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: [backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        if: github.actor != 'dependabot[bot]'
        run: |
          # setup / start ssh auth socket which manages our ssh keys when connecting to other servers via ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          # load the private key
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519
          # setup known hosts
          # FYI: SSH_KNOWN_HOSTS secret stores the result of 'ssh-keyscan remote-server.com'
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Download test coverage report
        uses: actions/download-artifact@v4
        with: 
          name: test-coverage-report

      - name: Deploy code coverage report to webserver
        if: github.actor != 'dependabot[bot]'
        run: scp coverage.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/group10/coverage.html

