name: CI-CD-Workshop

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Change to backend directory
        working-directory: /backend
        run: echo "Switched to root/backend"
      - name: Install dependencies
        working-directory: /backend
        run: go get .
      - name: Build
        working-directory: /backend
        run: go build -v ./...
      - name: Test with the Go CLI
        working-directory: /backend
        run: go test


        
