name: Trivy Dependency Scan
on:
  schedule:
    - cron: '0 0 * * *'  # Läuft täglich um Mitternacht
  workflow_dispatch: # Ermöglicht manuelle Ausführung

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
        - name: Setup SSH
          run: |
            # setup / start ssh auth socket which manages our ssh keys when connecting to other servers via ssh
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            # load the private key
            mkdir ~/.ssh
            chmod 700 ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-add ~/.ssh/id_ed25519
            # setup known hosts
            # FYI: SSH_KNOWN_HOSTS secret stores the result of 'ssh-keyscan remote-server.com'
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  
          
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.29.0
          with: 
            scan-type: "fs"
            scan-ref: .
            format: 'template'
            template: '@./trivy-html-report-template.tpl'
            output: 'trivy-scan-report.html'
      
        - name: Upload trivy scan report
          uses: actions/upload-artifact@v4
          with:
            name: trivy-scan-report
            path: ./trivy-scan-report.html
            retention-days: 14
      
        - name: Deploy code coverage report to webserver
          run: scp trivy-scan-report.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/group10/trivy-scan-report.html
                
